version: '2'
services:
 transmission:
  image: rickscherer/transmission-sabnzbd-openvpn
  privileged: true
  restart: always
  ports:
    - "9091:9091"
    - "9090:9090"
    - "8081:8081"
  dns:
    - 8.8.8.8
    - 8.8.4.4
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /your/storage/path/:/downloads
  environment:
    - OPENVPN_PROVIDER=PIA
    - OPENVPN_USERNAME=username
    - OPENVPN_PASSWORD=password
    - OPENVPN_OPTS="--inactive 3600 --ping 10 --ping-exit 60"
    - LOCAL_NETWORK=192.168.2.0/24
